### ISSUE TITLE
Large empty area - bottom page

### ISSUE THREAD

**Issue by Zemill** [Heroes-Profile/heroesprofile#659]
I dont remember seeing this before, but there is a large empty space at the bottom.  I dont think its caused by the changes I made to ads, but ¯\_(ツ)_/¯

![image](https://github.com/Heroes-Profile/heroesprofile/assets/33404722/9b3c2e8f-84a1-4ee8-8f82-3fa5849ba739)

**Comment by lifeinabstract** [comment]
This is because of the padding on the element surrounding the ad. The padding is still on the container even if the ad doesn't show. 
I tried a few things but they weren't successful. 
I tried removing the padding from the wrapper and adding it to the '.vm-placement' field instead, but this just made the ad bigger and it still overlapped, or it cut off part of the ad, which isn't good. 

The only way I can see that you could do this is after the ad script loads, to detect whether the div is empty or not. But you'd have to do it with a promise to ensure it did the check after the ad script had loaded, which I'm not sure is possible or worth it. 
@Zemill

**Comment by Zemill** [comment]
I will go in and pass-through the adblock value so we can make the padding dynamic based on whether adblock is enabled or not
