### ISSUE TITLE
Player MMR page is non-linear after uploading old games

### ISSUE THREAD

**Issue by jchorley** [Heroes-Profile/heroesprofile#905]
**Describe the bug**
After uploading old games, the player MMR page is confusing to interpret.

![Screenshot 2024-03-10 200350](https://github.com/Heroes-Profile/heroesprofile/assets/31038816/3655b7f2-931f-4612-b6f4-7815e697d155)

The `PlayerMMRController->getData()` method is sorting the data by the `mmr_date_parsed` instead of `game_date`. 

https://github.com/Heroes-Profile/heroesprofile/blob/v1.0.6/app/Http/Controllers/Player/PlayerMMRController.php#L111

This also means that rank tier is derived from the latest parsed result instead of latest player MMR by game time.

https://github.com/Heroes-Profile/heroesprofile/blob/v1.0.6/app/Http/Controllers/Player/PlayerMMRController.php#L163

Is this intentional?

**To Reproduce**
1. Load a player profile that has uploaded games out of order

Example: https://www.heroesprofile.com/Player/Cr4fty3/9821938/1/MMR

**Expected behavior**
MMR graph and table to be linear by game time

**Comment by Zemill** [comment]
We are currently running MMR recalculations

![image](https://github.com/Heroes-Profile/heroesprofile/assets/33404722/631c2822-babc-4ec1-b4f0-f05971c3bb6e)


With that said, specific to your questions.  It is intentional that the graph is based on parse date and not game date.  This is to account for situations where a player uploads their replays out of order.


Lets take the following example

Day 1: MMR 2015
Day 3: MMR 2020
Day 4: MMR 2021
Day 5: MMR 2030

Then they decide to upload the Day 2 game.  So that game would be based off the latest MMR, so Day 5.  Lets say they win again so now its 2032.  If we do it based on game date the order would look like

Day 1: MMR 2015
Day 2: MMR 2031
Day 3: MMR 2020
Day 4: MMR 2021
Day 5: MMR 2030

So you would have a random jump and drop at that day

![image](https://github.com/Heroes-Profile/heroesprofile/assets/33404722/8734f6a8-4634-4966-9e52-2046f6f55e40)


Versus the correct distribution of


![image](https://github.com/Heroes-Profile/heroesprofile/assets/33404722/ac262e86-44bc-4c34-859d-9a2796925e28)

**Comment by Zemill** [comment]
Forgot to mention the MMR value on your Profile page is the current real value.  As we go through the MMR Recalc process your MMR on the MMR page is going to be based on the recalc values
